### PR TITLE
Fix build

### LINKED ISSUE #37: TS Error: Namespace 'Intl' has no exported member 'Segmenter'
I just attempted to clone and built the project and ran into the following typescript error:

```
Error: .../ts-toolkit/shared/src/util/tokenizer/TextTokenizer.ts(40,29): semantic error TS2694: Namespace 'Intl' has no exported member 'Segmenter' ...
```

### Repro steps:

1. `git clone git@github.com:readium/ts-toolkit.git`
2. `cd ts-toolkit`
3. `pnpm install`

If I simply add some `@ts-ignore`'s to the `TextTokenizer.ts` (lines 40 & 50) the install completes successfully.

### Environment:

macOS@14
pnpm@8.15.7
node@21.7.1

### LINKED ISSUE #38: Build testapp vanilla error
When I run this testapp,
run `pnpm install`
occur this
> Creating entry file 616 ms
⠇ Building modules
│ (typescript) Error: /Users/sgalcheung/Downloads/ts-toolkit/shared/src/util/tokenizer/TextTokenizer.ts(40,29): semantic error TS2694: Namespace 'Intl' has no exported member 'Segmenter'.
│ Error: /Users/sgalcheung/Downloads/ts-toolkit/shared/src/util/tokenizer/TextTokenizer.ts(40,29): semantic error TS2694: Namespace 'Intl' has no exported member 'Segmenter'.in-typescript2/dist/rollup-plugin-typescript2.cjs.js:25006:12)
│     at error (/Users/sgalcheung/Downloads/ts-toolkit/node_modules/.pnpm/rollup@1.32.1/node_modules/rollup/dist/shared/node-entry.js:5400:30)@3.9.10/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29277:17)
│     at throwPluginError (/Users/sgalcheung/Downloads/ts-toolkit/node_modules/.pnpm/rollup@1.32.1/node_modules/rollup/dist/shared/node-entry.js:11878:12)
│     at Object.error (/Users/sgalcheung/Downloads/ts-toolkit/node_modules/.pnpm/rollup@1.32.1/node_modules/rollup/dist/shared/node-entry.js:12912:24)
│     at Object.error (/Users/sgalcheung/Downloads/ts-toolkit/node_modules/.pnpm/rollup@1.32.1/node_modules/rollup/dist/shared/node-entry.js:12081:38)
│     at RollupContext.error (/Users/sgalcheung/Downloads/ts-toolkit/node_modules/.pnpm/rollup-plugin-typescript2@0.27.3_rollup@1.32.1_typescript@3.9.10/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17237:30)
│     at /Users/sgalcheung/Downloads/ts-toolkit/node_modules/.pnpm/rollup-plugin-typescript2@0.27.3_rollup@1.32.1_typescript@3.9.10/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25033:23
│     at arrayEach (/Users/sgalcheung/Downloads/ts-toolkit/node_modules/.pnpm/rollup-plugin-typescript2@0.27.3_rollup@1.32.1_typescript@3.9.10/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:545:11)
│     at Function.forEach (/Users/sgalcheung/Downloads/ts-toolkit/node_modules/.pnpm/rollup-plugin-typescript2@0.27.3_rollup@1.32.1_typescript@3.9.10/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9397:14)
│     at printDiagnostics (/Users/sgalcheung/Downloads/ts-toolkit/node_modules/.pnpm/rollup-plugin-typescript2@0.27.3_rollup@1.32.1_typescript@3.9.10/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25006:12)
│     at Object.transform (/Users/sgalcheung/Downloads/ts-toolkit/node_modules/.pnpm/rollup-plugin-typescript2@0.27.3_rollup@1.32.1_typescript@3.9.10/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29277:17)
│     at /Users/sgalcheung/Downloads/ts-toolkit/node_modules/.pnpm/rollup@1.32.1/node_modules/rollup/dist/shared/node-entry.js:13117:25Namespace 'Intl' has no exported member 'Segmenter'.
│     at runNextTicks (node:internal/process/task_queues:60:5)
└─ Failed in 10s at /Users/sgalcheung/Downloads/ts-toolkit/shared
 ELIFECYCLE  Command failed with exit code 1.

my env

> sw_vers
ProductName:	macOS
ProductVersion:	12.7.4
BuildVersion:	21H1123
node -v
v21.7.3
pnpm --version
8.15.4
tsc --version
Version 5.4.5

### LINKED ISSUE #47: Module missing in navigator-html-injectables
While working on the build process, `tsc` made me aware `types/shared` is missing in `vendor/hypothesis/anchroning/api-types.ts`.

Here’s the raw message error.

```
src/vendor/hypothesis/anchoring/api-types.ts:1:43 - error TS2307: Cannot find module '../types/shared' or its corresponding type declarations.
1 import type { ClientAnnotationData } from '../types/shared';

Found 1 error in src/vendor/hypothesis/anchoring/api-types.ts:1

 ELIFECYCLE  Command failed with exit code 2.
```

### LINKED ISSUE #49: Some tools have issues with unicode property escapes in regex
It seems that the following:

https://github.com/readium/ts-toolkit/blob/711740799f670e661bad29e0fe023488c2e4477e/shared/src/util/tokenizer/TextTokenizer.ts#L119-L124

Specifically,

```
/[\p{L}\p{N}]+/u
```

make tools such as babel throw an error: 

```sh
Unknown property: L at matchProperty
```

[Could find something similar for RI and Emoji](https://stackoverflow.com/questions/73457529/unicode-property-escapes-in-regex-cause-errors-in-babel), with babel + NextJS involved.

### PR DESCRIPTION
**Pull request by JayPanoz**
This PR should fix the `build` script for all packages/workspaces in the repository, and make shared models testable again. 

It takes care of the following issues:

- it resolves #49;
- it resolves #47;
- it fixes #38;
- it fixes #37.

For consistency, ViteJS is now used across the board and `tsc` only emits definition types. Note the existing Github Workflow targeting `Shared` was slightly edited so checks can be passed, it doesn’t handle other packages ATM.

Note Vite will emit a warning because of ReadiumCSS inlined in Navigator but it hasn’t any negative effect:

```
[WARNING] "@namespace" rules are not supported [unsupported-@namespace]
```

As a sidenote, to do things properly the fonts’ license that are present in ReadiumCSS should be output with static assets in `dist` so this is something to keep in mind.

### CODE REVIEW

**Comment by JayPanoz** [comment]
OK so I’m not expecting to commit more changes at the moment, and I guess the PR is ready for review – and additions for `npm`.

Tried to follow `package.json` recommendations from ViteJS docs but maybe you see a better solution.

File: navigator/src/epub/frame/FrameComms.ts [hunk 1]
```diff
@@ -46,7 +46,7 @@ export class FrameComms {
         } catch (error) {
             this.channelId = mid();
         }
-        this.gc = setInterval(() => {
+        this.gc = window.setInterval(() => {
```
Comment (chocolatkey) [inline navigator/src/epub/frame/FrameComms.ts]: Why did you add `window` (here and other places)?

**Review by chocolatkey — APPROVED** [review]

File: navigator/src/epub/frame/FrameComms.ts (hunk 1 above)
Comment (JayPanoz) [reply navigator/src/epub/frame/FrameComms.ts]: That looked like the easiest way to fix TypeScript complaining of the `number` type as it thought it could be `NodeJS.Timer`. 

An alternative would be `ReturnType<typeof setTimeout>` but considering navigator is only intended to be used in browsers, it seemed like a more obvious option. Although I’d prefer to reach some agreement, obviously.

Comment (bluefirepatrick) [reply navigator/src/epub/frame/FrameComms.ts]: It seems like having gc be of type number makes sense -especially since clearInterval takes a number -and that window. facilitates that.  Just my two cents.  :)

**Review by bluefirepatrick — APPROVED** [review]

File: navigator/src/epub/frame/FrameComms.ts (hunk 1 above)
Comment (chocolatkey) [reply navigator/src/epub/frame/FrameComms.ts]: @JayPanoz OK, thanks for explaining. The reason why I ask is *technically* the frame communications part of the navigator is something that could be re-used in a non-browser scenario (like Thorium's Node.JS) to communicate with an iFrame. But that's a very theoretical case.

Comment (JayPanoz) [reply navigator/src/epub/frame/FrameComms.ts]: @chocolatkey Thanks for pointing that out. Removed it from navigator-html-injectables and changed the type so that it adapts to ts-config, kept it in navigator.

**Comment by JayPanoz** [comment]
Thanks for your feedback. 🙏
